version: '3.1'
services:
  koiplate-gateway-api:
    container_name: koiplate-gateway-api
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_INITDB_DATABASE: koiplate-gateway
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
    networks:
      - backend
volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge